Use `cargo hack` to test feature powerset
Also fix warnings in docs, and check that docs build without warnings in
CI and husky

https://github.com/roadster-rs/roadster/issues/28

diff --git a/.cargo-husky/hooks/pre-push b/.cargo-husky/hooks/pre-push
--- a/.cargo-husky/hooks/pre-push
+++ b/.cargo-husky/hooks/pre-push
@@ -1,8 +1,14 @@
 #!/usr/bin/env bash
 
+# Exit immediately if any command returns non-zero exit status.
+set -e
+
 # `fmt` doesn't depend on which features are enabled
 echo "### fmt --all --check ###"
 cargo fmt --all --check
+
+echo "### cargo doc --all-features --no-deps ###"
+RUSTDOCFLAGS="-D warnings" cargo doc --all-features --no-deps
 
 # With no features
 echo "### test --no-default-features --workspace ###"
